name = 'Ioannis alt:V Server'
host = '0.0.0.0'
port = 7788
players = 128
# password = 'ultra-password'
announce = false
debug = true
# token = 'YOUR_TOKEN'
gamemode = 'Reallife'
website = 'example.com'
language = 'de'
description = 'alt:V Sample Server'
modules = ['js-module', 'csharp-module']
resources = ['chat', 'AltVServer','AltVClientside']
